# Generated by Django 4.1.1 on 2022-09-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('section', models.CharField(choices=[('C', 'Core'), ('S', 'Stats'), ('M', 'Mechanics')], default='C', max_length=1)),
                ('publish_year', models.DateTimeField()),
                ('AS_only', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
