# Generated by Django 4.1.1 on 2022-09-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EB_app', '0004_exam_question_exams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_progress']},
        ),
    ]
