# Generated by Django 4.1.1 on 2022-09-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EB_app', '0005_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exams',
            field=models.ManyToManyField(blank=True, to='EB_app.exam'),
        ),
    ]
