# Generated by Django 4.1.1 on 2022-09-20 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EB_app', '0007_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EB_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ExamOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('exam_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EB_app.examorder')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='exams',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.AddField(
            model_name='examorderitem',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EB_app.question'),
        ),
    ]
