# Generated by Django 4.1.1 on 2022-09-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EB_app', '0009_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='order',
            new_name='examorder',
        ),
    ]
