# Generated by Django 4.1.1 on 2022-09-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EB_app', '0011_question_digital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examorderitem',
            old_name='quantity',
            new_name='is_item_ordered',
        ),
    ]
