# Generated by Django 4.1.1 on 2022-09-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EB_app', '0012_rename_quantity_examorderitem_is_item_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='examorderitem',
            name='exam_question_number',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True),
        ),
    ]
