# Generated by Django 4.1.1 on 2022-09-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EB_app', '0013_examorderitem_exam_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examorderitem',
            name='exam_question_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
