# Generated by Django 4.1.1 on 2022-09-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EB_app', '0015_alter_examorderitem_exam_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='examorder',
            name='question_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
