# Generated by Django 4.1.1 on 2022-09-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EB_app', '0016_examorder_question_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
