# Generated by Django 4.1.1 on 2022-09-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EB_app', '0017_question_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
