# Generated by Django 4.1.1 on 2022-09-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EB_app', '0018_alter_question_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('Core', 'Core'), ('Stats', 'Stats'), ('Mechanics', 'Mechanics')], default='Core', max_length=10),
        ),
    ]
